name: Run Tests

on: push

jobs:
  run-frontend-test:
    name: Run FE test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run tests
        working-directory: ./frontend
        run: npm run test

  run-backend-test:
    name: Run BE test
    needs: [run-frontend-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./backend
        run: npm install
      - name: Run tests
        working-directory: ./backend
        run: npm run test
